### PR TITLE
V1.0.8: Code Improvements and File Storage Improvements

### LINKED ISSUE #6: Users of the libary should be able to use it, for programs that is in Program Files
So save Ngrok in a place where, the user has perms to access it. Like \AppData\Roaming

### PR DESCRIPTION
**Pull request by nlogozzo**
- Created one async DownloadAndUnzipNgrokAsync() method. The method will not block the calling thread. Once the method returns you will know the download and unzip finished. No need for an event when the download finishs
- Reworked the PlatformCode. No need for a PlatformCode class when you can use polymorphism with the IPlatformStrategy interface directly.
- Added IDisposable to IPlatformStrategy as Process is disposable
- Added IDisposable to INgrokManager as the IPlatformStrategy used needs cleaning up
- Stores the files in the user's AppData folder instead of the current running directory

### CODE REVIEW

**Comment by entvex** [comment]
Dear @nlogozzo.
Thanks for forking the project and working on this pull request. I would Like to merge it, but the current state of this PR is that all of the unit tests failed, do they also fail on your system?

**Comment by nlogozzo** [comment]
@entvex Try now

**Comment by entvex** [comment]
I viewed it, unit tests still failing, do they run on your pc? Please join the discord, and lets have a chat :)

**Comment by entvex** [comment]
@nlogozzo Thanks for your input. I looked over it, and it seems like all tests works as they should on windows. So I'll accept. Thanks for your contribution. We ofc still need to debug it, tomorrow for issues you had.

**Comment by nlogozzo** [comment]
@entvex Sounds good! Yep the same issue I was having occurs with this version and the old version. However this rewrite makes working with the library much easier

**Pull request merged**
